apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautilus-server
  namespace: nautilus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nautilus-server
  template:
    metadata:
      labels:
        app: nautilus-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nautilus-server
        image: fossephate/nautilus-backend:latest
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 3Gi
        ports:
        - containerPort: 5076
          name: api
        command: ["/bin/bash", "-c"]
        args: ["python nautiluscast.py --host 0.0.0.0 --log-to-stdout"]
        env:
          - name: REDIS_HOST
            # value: redis-0.redis
            value: db-redis-nyc3-79075-do-user-1024997-0.b.db.ondigitalocean.com
          - name: REDIS_DB
            value: "2"
          - name: REDIS_PORT
            value: "25061"
          - name: REDIS_USERNAME
            value: default
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nautilus
                key: redis_password
          - name: WS_URL
            value: ws://node.perish.co:9952
          - name: RPC_URL
            value: http://node.perish.co:9950/proxy
          - name: WORK_URL
            value: http://node.perish.co:7090
          - name: DEBUG
            value: "0"
          - name: FCM_API_KEY
            valueFrom:
              secretKeyRef:
                name: nautilus
                key: fcm_api_key
          - name: FCM_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: nautilus
                key: fcm_sender
